name: APScheduler Test

permissions:
  contents: write

on:
  schedule:
    - cron: '*/5 * * * *'  # Every 5 minutes (UTC)
  workflow_dispatch: {}     # Allow manual triggering from GitHub UI

jobs:
  update-ev-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run odds.py (fetch raw odds)
        run: python odds.py

      - name: Run positiveev.py (calculate EV plays)
        run: python positiveev.py

      - name: Run line_movement.py (track line movements)
        run: python line_movement.py

      - name: Commit updated JSON files to GitHub
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"

          git add data/all_odds.json data/positive_ev_plays.json

          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            TIMESTAMP=$(date -u "+%Y-%m-%d %H:%M:%S UTC")
            git commit -m "🔁 Auto-update odds data — ${TIMESTAMP}"
            git push origin main
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload odds_data.db as artifact
        uses: actions/upload-artifact@v3
        with:
          name: odds-data
          path: data/odds_data.db
