name: APScheduler Test

permissions:
  contents: write

on:
  schedule:
    - cron: '*/5 * * * *'  # Every 5 minutes
  workflow_dispatch: {}     # Manual run enabled

jobs:
  update-ev-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run odds.py (fetch raw odds)
        run: python odds.py

      - name: Run positiveev.py (calculate EV)
        run: python positiveev.py

      - name: Run line_movement.py (track snapshots)
        run: python line_movement.py

      - name: Upload odds_data.db (SQLite)
        uses: actions/upload-artifact@v2
        with:
          name: odds-db
          path: data/odds_data.db

      - name: Upload positive_ev_plays.json
        uses: actions/upload-artifact@v2
        with:
          name: ev-plays
          path: data/positive_ev_plays.json

      - name: Upload all_odds.json
        uses: actions/upload-artifact@v3
        with:
          name: raw-odds
          path: data/all_odds.json
