name: APScheduler Test

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:     # Allows you to manually trigger the workflow

jobs:
  run-odds-service:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run odds_service.py
        env:
          # Pass any necessary environment variables or secrets here.
          # For example:
          # SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: |
          python odds_service.py
