name: APScheduler Test

permissions:
  contents: write
  
on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch: {}    # Allows manual triggering

jobs:
  run-odds-service:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Pull latest changes
        run: |
          git config pull.rebase false
          git pull origin main

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run odds_service.py
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          python odds_service.py

      - name: Commit updated positive EV bets and line movement files
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git add data/positive_ev_bets.json data/line_movement.json
          git commit -m "Update positive EV bets and line movement"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}